# Configuration de l'étiquetage automatique pour projet Java Maven
# Ce fichier définit quels labels sont appliqués automatiquement selon les fichiers modifiés

# Code Backend/Java
backend:
  - src/main/java/**
  - src/test/java/**

# Fichiers de configuration  
config:
  - pom.xml
  - ".github/**"
  - "*.xml"
  - "*.properties"
  - "*.yml"

# Fichiers Frontend/Web
frontend:
  - src/main/webapp/**
  - src/webapp/**
  - "**/*.jsp"
  - "**/*.css" 
  - "**/*.js"
  - "**/*.html"

# Build/Deploy
build:
  - build/**
  - target/**
  - "*.bat"
  - "*.sh"

# Documentation
documentation:
  - "**/*.md"
  - documentation/**

# Dépendances
dependencies:
  - lib/**
  - "**/*.jar"

# Sprint features (basé sur les noms de branches)
sprint:
  - any: ['sprint/**', 'feature/**']

# Staging
staging:
  - any: ['staging/**']

# Release
release:
  - any: ['release/**']

# Hotfix
hotfix:
  - any: ['hotfix/**', 'fix/**']